# SGE parameters
#$ -cwd                   # run in current directory
#$ -S /bin/bash           # Interpreting shell for the job
#$ -N unknowns                # Name of the job
#$ -V                     # .bashrc is read in all nodes
#$ -pe smp 1             # number of job slots to be reserved
#$ -l h_vmem=500G          # memory required
#$ -e error.log           # error file
#$ -o out.log             # output file
#$ -m abe                 # send an email at the beggining, end and if aborted
#$ -M guillems@ethz.ch

ml R
Rscript accum_genes.R
